spring:
  profiles:
    active: dev

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

  output:
    ansi:
      enabled: ALWAYS

ead:
  api:
    url:
      course: 'http://localhost:8082'