server:
  port: 8087

spring:
  application:
    name: ead-authuser-service
  profiles:
    active: dev

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

  output:
    ansi:
      enabled: ALWAYS

ead:
  api:
    url:
      course: 'http://ead-course-service'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost