name: Java CI with Maven

on:
  push:
    branches:
      - 'feature/*'
      - 'develop'
      - 'main'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Start MySQL
      run: docker-compose -f ./docker/docker-compose.yml up -d   
    - name: Build and Run Integration Tests with Maven
      run: mvn -B verify --file pom.xml
